module readConstants

contains

  subroutine read_constants(in_file,mode)
    use fileio_mod, only : fio_open, fio_read, fio_close
    use pftvarcon
    use Tracer_varcon
    use soilorder_varcon
    use elm_varcon
    use elm_varpar
    !#USE_START
    use AllocationMod
    use PhenologyMod
    use CH4varcon
    use CH4Mod
    use SharedParamsMod
    use SnowSnicarMod
    use PhotosynthesisMod
    use DecompCascadeBGCMod
    use DecompCascadeCNMod
    use SoilLittVertTranspMod
    use GapMortalityMod
    use SurfaceAlbedoMod
    use SoilLittDecompMod
    !#USE_END
    implicit none
    character(len=256),intent(in) :: in_file
    integer, intent(in) :: mode
    integer :: errcode

    call fio_open(18,in_file, 1)

  if(mode == 0) then
    !from elm_varpar
    call fio_read(18,"nlevsoi  ",nlevsoi  ,errcode=errcode)
    call fio_read(18,"nlevsoifl",nlevsoifl,errcode=errcode)
    call fio_read(18,"nlevgrnd ",nlevgrnd ,errcode=errcode)
    call fio_read(18,"nlevurb        ",nlevurb        ,errcode=errcode)
    call fio_read(18,"nlevlak        ",nlevlak        ,errcode=errcode)
    call fio_read(18,"nlevdecomp     ",nlevdecomp     ,errcode=errcode)
    call fio_read(18,"nlevdecomp_full",nlevdecomp_full,errcode=errcode)
    call fio_read(18,"nlevtrc_soil",nlevtrc_soil,errcode=errcode)
    call fio_read(18,"nlevtrc_full",nlevtrc_full,errcode=errcode)

  else
    !from pftconrd
    call fio_read(18,"dleaf    ",dleaf    ,errcode=errcode)
    call fio_read(18,"c3psn    ",c3psn    ,errcode=errcode)
    call fio_read(18,"xl       ",xl       ,errcode=errcode)
    call fio_read(18,"rhol     ",rhol     ,errcode=errcode)
    call fio_read(18,"rhos     ",rhos     ,errcode=errcode)
    call fio_read(18,"taul     ",taul     ,errcode=errcode)
    call fio_read(18,"taus     ",taus     ,errcode=errcode)
    call fio_read(18,"z0mr     ",z0mr     ,errcode=errcode)
    call fio_read(18,"displar  ",displar  ,errcode=errcode)
    call fio_read(18,"roota_par",roota_par,errcode=errcode)
    call fio_read(18,"rootb_par",rootb_par,errcode=errcode)
    call fio_read(18,"crop     ",crop     ,errcode=errcode)
    call fio_read(18,"irrigated",irrigated,errcode=errcode)
    call fio_read(18,"smpso    ",smpso    ,errcode=errcode)
    call fio_read(18,"smpsc    ",smpsc    ,errcode=errcode)
    call fio_read(18,"fnitr    ",fnitr    ,errcode=errcode)
    call fio_read(18,"slatop   ",slatop   ,errcode=errcode)
    call fio_read(18,"dsladlai ",dsladlai ,errcode=errcode)
    call fio_read(18,"leafcn   ",leafcn   ,errcode=errcode)
    call fio_read(18,"flnr     ",flnr     ,errcode=errcode)
    call fio_read(18,"woody    ",woody    ,errcode=errcode)
    call fio_read(18,"lflitcn  ",lflitcn  ,errcode=errcode)
    call fio_read(18,"frootcn  ",frootcn  ,errcode=errcode)
    call fio_read(18,"livewdcn ",livewdcn ,errcode=errcode)
    call fio_read(18,"deadwdcn ",deadwdcn ,errcode=errcode)

    call fio_read(18,"leafcp       ",leafcp       ,errcode=errcode)
    call fio_read(18,"lflitcp      ",lflitcp      ,errcode=errcode)
    call fio_read(18,"frootcp      ",frootcp      ,errcode=errcode)
    call fio_read(18,"livewdcp     ",livewdcp     ,errcode=errcode)
    call fio_read(18,"deadwdcp     ",deadwdcp     ,errcode=errcode)
    call fio_read(18,"grperc       ",grperc       ,errcode=errcode)
    call fio_read(18,"grpnow       ",grpnow       ,errcode=errcode)
    call fio_read(18,"rootprof_beta",rootprof_beta,errcode=errcode)
    call fio_read(18,"graincn      ",graincn      ,errcode=errcode)
    call fio_read(18,"graincp      ",graincp      ,errcode=errcode)
    call fio_read(18,"mxtmp        ",mxtmp        ,errcode=errcode)
    call fio_read(18,"baset        ",baset        ,errcode=errcode)
    call fio_read(18,"declfact     ",declfact     ,errcode=errcode)
    call fio_read(18,"bfact        ",bfact        ,errcode=errcode)
    call fio_read(18,"aleaff       ",aleaff       ,errcode=errcode)
    call fio_read(18,"arootf       ",arootf       ,errcode=errcode)
    call fio_read(18,"astemf       ",astemf       ,errcode=errcode)
    call fio_read(18,"arooti       ",arooti       ,errcode=errcode)
    call fio_read(18,"fleafi       ",fleafi       ,errcode=errcode)
    call fio_read(18,"allconsl     ",allconsl     ,errcode=errcode)
    call fio_read(18,"allconss     ",allconss     ,errcode=errcode)
    call fio_read(18,"ztopmx       ",ztopmx       ,errcode=errcode)
    call fio_read(18,"laimx        ",laimx        ,errcode=errcode)
    call fio_read(18,"gddmin       ",gddmin       ,errcode=errcode)
    call fio_read(18,"hybgdd       ",hybgdd       ,errcode=errcode)
    call fio_read(18,"lfemerg      ",lfemerg      ,errcode=errcode)
    call fio_read(18,"grnfill      ",grnfill      ,errcode=errcode)
    call fio_read(18,"mxmat        ",mxmat        ,errcode=errcode)
    call fio_read(18,"mnNHplantdate",mnNHplantdate,errcode=errcode)
    call fio_read(18,"mxNHplantdate",mxNHplantdate,errcode=errcode)
    call fio_read(18,"mnSHplantdate",mnSHplantdate,errcode=errcode)
    call fio_read(18,"mxSHplantdate",mxSHplantdate,errcode=errcode)
    call fio_read(18,"planttemp    ",planttemp    ,errcode=errcode)
    call fio_read(18,"minplanttemp ",minplanttemp ,errcode=errcode)
    call fio_read(18,"froot_leaf   ",froot_leaf   ,errcode=errcode)
    call fio_read(18,"stem_leaf    ",stem_leaf    ,errcode=errcode)
    call fio_read(18,"croot_stem   ",croot_stem   ,errcode=errcode)
    call fio_read(18,"flivewd      ",flivewd      ,errcode=errcode)
    call fio_read(18,"fcur         ",fcur         ,errcode=errcode)
    call fio_read(18,"lf_flab      ",lf_flab      ,errcode=errcode)
    call fio_read(18,"lf_fcel      ",lf_fcel      ,errcode=errcode)
    call fio_read(18,"lf_flig      ",lf_flig      ,errcode=errcode)
    call fio_read(18,"fr_flab      ",fr_flab      ,errcode=errcode)
    call fio_read(18,"fr_fcel      ",fr_fcel      ,errcode=errcode)
    call fio_read(18,"fr_flig      ",fr_flig      ,errcode=errcode)
    call fio_read(18,"leaf_long    ",leaf_long    ,errcode=errcode)
    call fio_read(18,"froot_long   ",froot_long   ,errcode=errcode)
    call fio_read(18,"evergreen    ",evergreen    ,errcode=errcode)
    call fio_read(18,"stress_decid ",stress_decid ,errcode=errcode)
    call fio_read(18,"season_decid ",season_decid ,errcode=errcode)
    call fio_read(18,"pconv        ",pconv        ,errcode=errcode)
    call fio_read(18,"pprod10      ",pprod10      ,errcode=errcode)
    call fio_read(18,"pprod100     ",pprod100     ,errcode=errcode)
    call fio_read(18,"pprodharv10  ",pprodharv10  ,errcode=errcode)
    call fio_read(18,"cc_leaf      ",cc_leaf      ,errcode=errcode)
    call fio_read(18,"cc_lstem     ",cc_lstem     ,errcode=errcode)
    call fio_read(18,"cc_dstem     ",cc_dstem     ,errcode=errcode)
    call fio_read(18,"cc_other     ",cc_other     ,errcode=errcode)
    call fio_read(18,"fm_leaf      ",fm_leaf      ,errcode=errcode)
    call fio_read(18,"fm_lstem     ",fm_lstem     ,errcode=errcode)
    call fio_read(18,"fm_dstem     ",fm_dstem     ,errcode=errcode)
    call fio_read(18,"fm_other     ",fm_other     ,errcode=errcode)
    call fio_read(18,"fm_root      ",fm_root      ,errcode=errcode)
    call fio_read(18,"fm_lroot     ",fm_lroot     ,errcode=errcode)
    call fio_read(18,"fm_droot     ",fm_droot     ,errcode=errcode)
    call fio_read(18,"fsr_pft      ",fsr_pft      ,errcode=errcode)
    call fio_read(18,"fd_pft       ",fd_pft       ,errcode=errcode)
    call fio_read(18,"fertnitro    ",fertnitro    ,errcode=errcode)
    call fio_read(18,"fleafcn      ",fleafcn      ,errcode=errcode)
    call fio_read(18,"ffrootcn     ",ffrootcn     ,errcode=errcode)
    call fio_read(18,"fstemcn      ",fstemcn      ,errcode=errcode)
    call fio_read(18,"presharv     ",presharv     ,errcode=errcode)
    call fio_read(18,"convfact     ",convfact     ,errcode=errcode)
    call fio_read(18,"fyield       ",fyield       ,errcode=errcode)
    call fio_read(18,"root_dmx     ",root_dmx     ,errcode=errcode)

    call fio_read(18,"VMAX_PLANT_NH4",VMAX_PLANT_NH4,errcode=errcode)
    call fio_read(18,"VMAX_PLANT_NO3",VMAX_PLANT_NO3,errcode=errcode)
    call fio_read(18,"VMAX_PLANT_P  ",VMAX_PLANT_P  ,errcode=errcode)
    call fio_read(18,"VMAX_MINSURF_P_vr",VMAX_MINSURF_P_vr,errcode=errcode)
    call fio_read(18,"KM_PLANT_NH4",KM_PLANT_NH4,errcode=errcode)
    call fio_read(18,"KM_PLANT_NO3",KM_PLANT_NO3,errcode=errcode)
    call fio_read(18,"KM_PLANT_P  ",KM_PLANT_P  ,errcode=errcode)
    call fio_read(18,"KM_MINSURF_P_vr    ",KM_MINSURF_P_vr    ,errcode=errcode)
    call fio_read(18,"decompmicc_patch_vr",decompmicc_patch_vr,errcode=errcode)
    call fio_read(18,"VMAX_PTASE ",VMAX_PTASE ,errcode=errcode)
    call fio_read(18,"i_vc       ",i_vc       ,errcode=errcode)
    call fio_read(18,"s_vc       ",s_vc       ,errcode=errcode)
    call fio_read(18,"alpha_nfix ",alpha_nfix ,errcode=errcode)
    call fio_read(18,"alpha_ptase",alpha_ptase,errcode=errcode)
    call fio_read(18,"ccost_nfix ",ccost_nfix ,errcode=errcode)
    call fio_read(18,"pcost_nfix ",pcost_nfix ,errcode=errcode)
    call fio_read(18,"ccost_ptase",ccost_ptase,errcode=errcode)
    call fio_read(18,"ncost_ptase",ncost_ptase,errcode=errcode)
    call fio_read(18,"VMAX_NFIX  ",VMAX_NFIX  ,errcode=errcode)
    call fio_read(18,"KM_NFIX    ",KM_NFIX    ,errcode=errcode)
    call fio_read(18,"leafcn_obs       ",leafcn_obs       ,errcode=errcode)
    call fio_read(18,"frootcn_obs      ",frootcn_obs      ,errcode=errcode)
    call fio_read(18,"livewdcn_obs     ",livewdcn_obs     ,errcode=errcode)
    call fio_read(18,"deadwdcn_obs     ",deadwdcn_obs     ,errcode=errcode)
    call fio_read(18,"leafcp_obs       ",leafcp_obs       ,errcode=errcode)
    call fio_read(18,"frootcp_obs      ",frootcp_obs      ,errcode=errcode)
    call fio_read(18,"livewdcp_obs     ",livewdcp_obs     ,errcode=errcode)
    call fio_read(18,"deadwdcp_obs     ",deadwdcp_obs     ,errcode=errcode)
    call fio_read(18,"leafcn_obs_flex  ",leafcn_obs_flex  ,errcode=errcode)
    call fio_read(18,"frootcn_obs_flex ",frootcn_obs_flex ,errcode=errcode)
    call fio_read(18,"livewdcn_obs_flex",livewdcn_obs_flex,errcode=errcode)
    call fio_read(18,"deadwdcn_obs_flex",deadwdcn_obs_flex,errcode=errcode)
    call fio_read(18,"leafcp_obs_flex  ",leafcp_obs_flex  ,errcode=errcode)
    call fio_read(18,"frootcp_obs_flex ",frootcp_obs_flex ,errcode=errcode)
    call fio_read(18,"livewdcp_obs_flex",livewdcp_obs_flex,errcode=errcode)
    call fio_read(18,"deadwdcp_obs_flex",deadwdcp_obs_flex,errcode=errcode)
    call fio_read(18,"vcmax_np1        ",vcmax_np1        ,errcode=errcode)
    call fio_read(18,"vcmax_np2        ",vcmax_np2        ,errcode=errcode)
    call fio_read(18,"vcmax_np3        ",vcmax_np3        ,errcode=errcode)
    call fio_read(18,"vcmax_np4        ",vcmax_np4        ,errcode=errcode)
    call fio_read(18,"fnr     ",fnr    ,errcode=errcode)
    call fio_read(18,"act25   ",act25  ,errcode=errcode)
    call fio_read(18,"kcha    ",kcha   ,errcode=errcode)
    call fio_read(18,"koha    ",koha   ,errcode=errcode)
    call fio_read(18,"cpha    ",cpha   ,errcode=errcode)
    call fio_read(18,"vcmaxha ",vcmaxha,errcode=errcode)
    call fio_read(18,"jmaxha  ",jmaxha ,errcode=errcode)
    call fio_read(18,"tpuha   ",tpuha  ,errcode=errcode)
    call fio_read(18,"lmrha   ",lmrha  ,errcode=errcode)
    call fio_read(18,"vcmaxhd ",vcmaxhd,errcode=errcode)
    call fio_read(18,"jmaxhd  ",jmaxhd ,errcode=errcode)
    call fio_read(18,"tpuhd   ",tpuhd  ,errcode=errcode)
    call fio_read(18,"lmrhd   ",lmrhd  ,errcode=errcode)
    call fio_read(18,"lmrse   ",lmrse  ,errcode=errcode)
    call fio_read(18,"qe      ",qe     ,errcode=errcode)
    call fio_read(18,"theta_cj",theta_cj,errcode=errcode)
    call fio_read(18,"bbbopt  ",bbbopt ,errcode=errcode)
    call fio_read(18,"mbbopt  ",mbbopt ,errcode=errcode)
    call fio_read(18,"nstor   ",nstor  ,errcode=errcode)
    call fio_read(18,"br_xr   ",br_xr  ,errcode=errcode)

    call fio_read(18,"noveg                  ",noveg               ,errcode=errcode)
    call fio_read(18,"ndllf_evr_tmp_tree     ",ndllf_evr_tmp_tree  ,errcode=errcode)
    call fio_read(18,"ndllf_evr_brl_tree     ",ndllf_evr_brl_tree  ,errcode=errcode)
    call fio_read(18,"ndllf_dcd_brl_tree     ",ndllf_dcd_brl_tree  ,errcode=errcode)
    call fio_read(18,"nbrdlf_evr_trp_tree    ",nbrdlf_evr_trp_tree ,errcode=errcode)
    call fio_read(18,"nbrdlf_evr_tmp_tree    ",nbrdlf_evr_tmp_tree ,errcode=errcode)
    call fio_read(18,"nbrdlf_dcd_trp_tree    ",nbrdlf_dcd_trp_tree ,errcode=errcode)
    call fio_read(18,"nbrdlf_dcd_tmp_tree    ",nbrdlf_dcd_tmp_tree ,errcode=errcode)
    call fio_read(18,"nbrdlf_dcd_brl_tree    ",nbrdlf_dcd_brl_tree ,errcode=errcode)
    call fio_read(18,"ntree                  ",ntree               ,errcode=errcode)
    call fio_read(18,"nbrdlf_evr_shrub       ",nbrdlf_evr_shrub    ,errcode=errcode)
    call fio_read(18,"nbrdlf_dcd_tmp_shrub   ",nbrdlf_dcd_tmp_shrub,errcode=errcode)
    call fio_read(18,"nbrdlf_dcd_brl_shrub   ",nbrdlf_dcd_brl_shrub,errcode=errcode)
    call fio_read(18,"nc3_arctic_grass       ",nc3_arctic_grass    ,errcode=errcode)
    call fio_read(18,"nc3_nonarctic_grass    ",nc3_nonarctic_grass ,errcode=errcode)
    call fio_read(18,"nc4_grass              ",nc4_grass           ,errcode=errcode)
    call fio_read(18,"npcropmin              ",npcropmin           ,errcode=errcode)
    call fio_read(18,"ncorn                  ",ncorn               ,errcode=errcode)
    call fio_read(18,"ncornirrig             ",ncornirrig          ,errcode=errcode)
    call fio_read(18,"nscereal               ",nscereal            ,errcode=errcode)
    call fio_read(18,"nscerealirrig          ",nscerealirrig       ,errcode=errcode)
    call fio_read(18,"nwcereal               ",nwcereal            ,errcode=errcode)
    call fio_read(18,"nwcerealirrig          ",nwcerealirrig       ,errcode=errcode)
    call fio_read(18,"nsoybean               ",nsoybean            ,errcode=errcode)
    call fio_read(18,"nsoybeanirrig          ",nsoybeanirrig       ,errcode=errcode)
    call fio_read(18,"npcropmax              ",npcropmax           ,errcode=errcode)
    call fio_read(18,"nc3crop                ",nc3crop             ,errcode=errcode)
    call fio_read(18,"nc3irrig               ",nc3irrig            ,errcode=errcode)

    !-------- elm_varcon --------- !
    call fio_read(18,"zlak ",zlak ,errcode=errcode)
    call fio_read(18,"dzlak",dzlak,errcode=errcode)
    call fio_read(18,"zsoi ",zsoi ,errcode=errcode)
    call fio_read(18,"dzsoi",dzsoi,errcode=errcode)
    call fio_read(18,"zisoi",zisoi,errcode=errcode)
    call fio_read(18,"dzsoi_decomp",dzsoi_decomp,errcode=errcode)
    call fio_read(18,"nlvic  ",nlvic  ,errcode=errcode)
    call fio_read(18,"dzvic  ",dzvic  ,errcode=errcode)
    call fio_read(18,"zsoifl ",zsoifl ,errcode=errcode)
    call fio_read(18,"zisoifl",zisoifl,errcode=errcode)
    call fio_read(18,"dzsoifl",dzsoifl,errcode=errcode)

    !-------soilorder_varcon ------------------ !
    call fio_read(18,"smax            ",smax            ,errcode=errcode)
    call fio_read(18,"ks_sorption     ",ks_sorption     ,errcode=errcode)
    call fio_read(18,"r_weather       ",r_weather       ,errcode=errcode)
    call fio_read(18,"r_adsorp        ",r_adsorp        ,errcode=errcode)
    call fio_read(18,"r_desorp        ",r_desorp        ,errcode=errcode)
    call fio_read(18,"r_occlude       ",r_occlude       ,errcode=errcode)
    call fio_read(18,"k_s1_biochem    ",k_s1_biochem    ,errcode=errcode)
    call fio_read(18,"k_s2_biochem    ",k_s2_biochem    ,errcode=errcode)
    call fio_read(18,"k_s3_biochem    ",k_s3_biochem    ,errcode=errcode)
    call fio_read(18,"k_s4_biochem    ",k_s4_biochem    ,errcode=errcode)
    call fio_read(18,"r_mort_soilorder",r_mort_soilorder,errcode=errcode)

    !-----AllocParamsInst --------!
    #ifdef ALLOCATIONMOD
      call fio_read(18,"AllocParamsInst%bdnr             ",AllocParamsInst%bdnr             ,errcode=errcode)
      call fio_read(18,"AllocParamsInst%dayscrecover     ",AllocParamsInst%dayscrecover     ,errcode=errcode)
      call fio_read(18,"AllocParamsInst%compet_plant_no3 ",AllocParamsInst%compet_plant_no3 ,errcode=errcode)
      call fio_read(18,"AllocParamsInst%compet_plant_nh4 ",AllocParamsInst%compet_plant_nh4 ,errcode=errcode)
      call fio_read(18,"AllocParamsInst%compet_decomp_no3",AllocParamsInst%compet_decomp_no3,errcode=errcode)
      call fio_read(18,"AllocParamsInst%compet_decomp_nh4",AllocParamsInst%compet_decomp_nh4,errcode=errcode)
      call fio_read(18,"AllocParamsInst%compet_denit     ",AllocParamsInst%compet_denit     ,errcode=errcode)
      call fio_read(18,"AllocParamsInst%compet_nit       ",AllocParamsInst%compet_nit       ,errcode=errcode)
    #endif

    !---- PhenolParamsInst -----!
    #ifdef PHENOLOGYMOD
      call fio_read(18,"PhenolParamsInst%crit_dayl       ",PhenolParamsInst%crit_dayl       ,errcode=errcode)
      call fio_read(18,"PhenolParamsInst%crit_dayl_stress",PhenolParamsInst%crit_dayl_stress,errcode=errcode)
      call fio_read(18,"PhenolParamsInst%cumprec_onset   ",PhenolParamsInst%cumprec_onset   ,errcode=errcode)
      call fio_read(18,"PhenolParamsInst%ndays_on        ",PhenolParamsInst%ndays_on        ,errcode=errcode)
      call fio_read(18,"PhenolParamsInst%ndays_off       ",PhenolParamsInst%ndays_off       ,errcode=errcode)
      call fio_read(18,"PhenolParamsInst%fstor2tran      ",PhenolParamsInst%fstor2tran      ,errcode=errcode)
      call fio_read(18,"PhenolParamsInst%crit_onset_fdd  ",PhenolParamsInst%crit_onset_fdd  ,errcode=errcode)
      call fio_read(18,"PhenolParamsInst%crit_onset_swi  ",PhenolParamsInst%crit_onset_swi  ,errcode=errcode)
      call fio_read(18,"PhenolParamsInst%soilpsi_on      ",PhenolParamsInst%soilpsi_on      ,errcode=errcode)
      call fio_read(18,"PhenolParamsInst%crit_offset_fdd ",PhenolParamsInst%crit_offset_fdd ,errcode=errcode)
      call fio_read(18,"PhenolParamsInst%crit_offset_swi ",PhenolParamsInst%crit_offset_swi ,errcode=errcode)
      call fio_read(18,"PhenolParamsInst%soilpsi_off     ",PhenolParamsInst%soilpsi_off     ,errcode=errcode)
      call fio_read(18,"PhenolParamsInst%lwtop           ",PhenolParamsInst%lwtop           ,errcode=errcode)
    #endif

    ! -------------- Shared ---------- !
    #ifdef SHAREDPARAMSMOD
      call fio_read(18,"ParamsShareInst%Q10_mr               ",ParamsShareInst%Q10_mr               ,errcode=errcode)
      call fio_read(18,"ParamsShareInst%Q10_hr               ",ParamsShareInst%Q10_hr               ,errcode=errcode)
      call fio_read(18,"ParamsShareInst%minpsi               ",ParamsShareInst%minpsi               ,errcode=errcode)
      call fio_read(18,"ParamsShareInst%cwd_fcel             ",ParamsShareInst%cwd_fcel             ,errcode=errcode)
      call fio_read(18,"ParamsShareInst%cwd_flig             ",ParamsShareInst%cwd_flig             ,errcode=errcode)
      call fio_read(18,"ParamsShareInst%froz_q10             ",ParamsShareInst%froz_q10             ,errcode=errcode)
      call fio_read(18,"ParamsShareInst%decomp_depth_efolding",ParamsShareInst%decomp_depth_efolding,errcode=errcode)
      call fio_read(18,"ParamsShareInst%mino2lim             ",ParamsShareInst%mino2lim             ,errcode=errcode)
      call fio_read(18,"ParamsShareInst%organic_max          ",ParamsShareInst%organic_max          ,errcode=errcode)
    #endif

    !---- SnowSnicar -------------
    #ifdef SNOWSNICARMOD
      call fio_read(18,"snowage_tau  ",snowage_tau  ,errcode=errcode)
      call fio_read(18,"snowage_kappa",snowage_kappa,errcode=errcode)
      call fio_read(18,"snowage_drdt0",snowage_drdt0,errcode=errcode)
      call fio_read(18,"ss_alb_snw_drc     ",ss_alb_snw_drc     ,errcode=errcode)
      call fio_read(18,"asm_prm_snw_drc    ",asm_prm_snw_drc    ,errcode=errcode)
      call fio_read(18,"ext_cff_mss_snw_drc",ext_cff_mss_snw_drc,errcode=errcode)
      call fio_read(18,"ss_alb_snw_dfs     ",ss_alb_snw_dfs     ,errcode=errcode)
      call fio_read(18,"asm_prm_snw_dfs    ",asm_prm_snw_dfs    ,errcode=errcode)
      call fio_read(18,"ext_cff_mss_snw_dfs",ext_cff_mss_snw_dfs,errcode=errcode)

      call fio_read(18,"bcenh          ",bcenh          ,errcode=errcode)
      call fio_read(18,"ss_alb_bc1     ",ss_alb_bc1     ,errcode=errcode)
      call fio_read(18,"asm_prm_bc1    ",asm_prm_bc1    ,errcode=errcode)
      call fio_read(18,"ext_cff_mss_bc1",ext_cff_mss_bc1,errcode=errcode)
      call fio_read(18,"ss_alb_bc2     ",ss_alb_bc2     ,errcode=errcode)
      call fio_read(18,"asm_prm_bc2    ",asm_prm_bc2    ,errcode=errcode)
      call fio_read(18,"ext_cff_mss_bc2",ext_cff_mss_bc2,errcode=errcode)
      call fio_read(18,"ss_alb_oc1      ",ss_alb_oc1      ,errcode=errcode)
      call fio_read(18,"asm_prm_oc1     ",asm_prm_oc1     ,errcode=errcode)
      call fio_read(18,"ext_cff_mss_oc1 ",ext_cff_mss_oc1 ,errcode=errcode)
      call fio_read(18,"ss_alb_oc2      ",ss_alb_oc2      ,errcode=errcode)
      call fio_read(18,"asm_prm_oc2     ",asm_prm_oc2     ,errcode=errcode)
      call fio_read(18,"ext_cff_mss_oc2 ",ext_cff_mss_oc2 ,errcode=errcode)
      call fio_read(18,"ss_alb_dst1     ",ss_alb_dst1     ,errcode=errcode)
      call fio_read(18,"asm_prm_dst1    ",asm_prm_dst1    ,errcode=errcode)
      call fio_read(18,"ext_cff_mss_dst1",ext_cff_mss_dst1,errcode=errcode)
      call fio_read(18,"ss_alb_dst2     ",ss_alb_dst2     ,errcode=errcode)
      call fio_read(18,"asm_prm_dst2    ",asm_prm_dst2    ,errcode=errcode)
      call fio_read(18,"ext_cff_mss_dst2",ext_cff_mss_dst2,errcode=errcode)
      call fio_read(18,"ss_alb_dst3     ",ss_alb_dst3     ,errcode=errcode)
      call fio_read(18,"asm_prm_dst3    ",asm_prm_dst3    ,errcode=errcode)
      call fio_read(18,"ext_cff_mss_dst3",ext_cff_mss_dst3,errcode=errcode)
      call fio_read(18,"ss_alb_dst4     ",ss_alb_dst4     ,errcode=errcode)
      call fio_read(18,"asm_prm_dst4    ",asm_prm_dst4    ,errcode=errcode)
      call fio_read(18,"ext_cff_mss_dst4",ext_cff_mss_dst4,errcode=errcode)
    #endif

    !!! PhotosynthesisMod
    #ifdef PhotosynthesisMod
      call fio_read(18,"params_inst%krmax       ",params_inst%krmax       ,errcode=errcode)
      call fio_read(18,"params_inst%kmax        ",params_inst%kmax        ,errcode=errcode)
      call fio_read(18,"params_inst%psi50       ",params_inst%psi50       ,errcode=errcode)
      call fio_read(18,"params_inst%ck          ",params_inst%ck          ,errcode=errcode)
      call fio_read(18,"params_inst%psi_soil_ref",params_inst%psi_soil_ref,errcode=errcode)
    #endif

    !! CH4Mod !!
    #ifdef CH4MOD
    call fio_read(18, "CH4ParamsInst%q10ch4              ",CH4ParamsInst%q10ch4              ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%q10ch4base          ",CH4ParamsInst%q10ch4base          ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%f_ch4               ",CH4ParamsInst%f_ch4               ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%rootlitfrac         ",CH4ParamsInst%rootlitfrac         ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%cnscalefactor       ",CH4ParamsInst%cnscalefactor       ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%redoxlag            ",CH4ParamsInst%redoxlag            ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%lake_decomp_fact    ",CH4ParamsInst%lake_decomp_fact    ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%redoxlag_vertical   ",CH4ParamsInst%redoxlag_vertical   ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%pHmax               ",CH4ParamsInst%pHmax               ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%pHmin               ",CH4ParamsInst%pHmin               ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%oxinhib             ",CH4ParamsInst%oxinhib             ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%vmax_ch4_oxid       ",CH4ParamsInst%vmax_ch4_oxid       ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%k_m                 ",CH4ParamsInst%k_m                 ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%q10_ch4oxid         ",CH4ParamsInst%q10_ch4oxid         ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%smp_crit            ",CH4ParamsInst%smp_crit            ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%k_m_o2              ",CH4ParamsInst%k_m_o2              ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%k_m_unsat           ",CH4ParamsInst%k_m_unsat           ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%vmax_oxid_unsat     ",CH4ParamsInst%vmax_oxid_unsat     ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%aereoxid            ",CH4ParamsInst%aereoxid            ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%scale_factor_aere   ",CH4ParamsInst%scale_factor_aere   ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%nongrassporosratio  ",CH4ParamsInst%nongrassporosratio  ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%unsat_aere_ratio    ",CH4ParamsInst%unsat_aere_ratio    ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%porosmin            ",CH4ParamsInst%porosmin            ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%vgc_max             ",CH4ParamsInst%vgc_max             ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%satpow              ",CH4ParamsInst%satpow              ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%scale_factor_gasdiff",CH4ParamsInst%scale_factor_gasdiff,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%scale_factor_liqdiff",CH4ParamsInst%scale_factor_liqdiff,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%capthick            ",CH4ParamsInst%capthick            ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%f_sat               ",CH4ParamsInst%f_sat               ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%qflxlagd            ",CH4ParamsInst%qflxlagd            ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%highlatfact         ",CH4ParamsInst%highlatfact         ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%q10lakebase         ",CH4ParamsInst%q10lakebase         ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%atmch4              ",CH4ParamsInst%atmch4              ,errcode=errcode)
    call fio_read(18, "CH4ParamsInst%rob                 ",CH4ParamsInst%rob                 ,errcode=errcode)
    #endif

    !!! DecompCascadeBGCMod
    if((.not. is_active_betr_bgc) .and. use_century_decomp) then
    #ifdef DECOMPCASCADEBGCMOD
    call fio_read(18,"DecompBGCParamsInst%cn_s1_bgc    ",DecompBGCParamsInst%cn_s1_bgc    ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%cn_s2_bgc    ",DecompBGCParamsInst%cn_s2_bgc    ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%cn_s3_bgc    ",DecompBGCParamsInst%cn_s3_bgc    ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%np_s1_new_bgc",DecompBGCParamsInst%np_s1_new_bgc,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%np_s2_new_bgc",DecompBGCParamsInst%np_s2_new_bgc,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%np_s3_new_bgc",DecompBGCParamsInst%np_s3_new_bgc,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%cp_s1_new_bgc",DecompBGCParamsInst%cp_s1_new_bgc,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%cp_s2_new_bgc",DecompBGCParamsInst%cp_s2_new_bgc,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%cp_s3_new_bgc",DecompBGCParamsInst%cp_s3_new_bgc,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%rf_l1s1_bgc  ",DecompBGCParamsInst%rf_l1s1_bgc  ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%rf_l2s1_bgc  ",DecompBGCParamsInst%rf_l2s1_bgc  ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%rf_l3s2_bgc  ",DecompBGCParamsInst%rf_l3s2_bgc  ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%rf_s2s1_bgc  ",DecompBGCParamsInst%rf_s2s1_bgc  ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%rf_s2s3_bgc  ",DecompBGCParamsInst%rf_s2s3_bgc  ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%rf_s3s1_bgc  ",DecompBGCParamsInst%rf_s3s1_bgc  ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%rf_cwdl2_bgc ",DecompBGCParamsInst%rf_cwdl2_bgc ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%rf_cwdl3_bgc ",DecompBGCParamsInst%rf_cwdl3_bgc ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%tau_l1_bgc   ",DecompBGCParamsInst%tau_l1_bgc   ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%tau_l2_l3_bgc",DecompBGCParamsInst%tau_l2_l3_bgc,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%tau_s1_bgc   ",DecompBGCParamsInst%tau_s1_bgc   ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%tau_s2_bgc   ",DecompBGCParamsInst%tau_s2_bgc   ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%tau_s3_bgc   ",DecompBGCParamsInst%tau_s3_bgc   ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%tau_cwd_bgc  ",DecompBGCParamsInst%tau_cwd_bgc  ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%cwd_fcel_bgc ",DecompBGCParamsInst%cwd_fcel_bgc ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%cwd_flig_bgc ",DecompBGCParamsInst%cwd_flig_bgc ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%k_frag_bgc   ",DecompBGCParamsInst%k_frag_bgc   ,errcode=errcode)
    call fio_read(18,"DecompBGCParamsInst%minpsi_bgc   ",DecompBGCParamsInst%minpsi_bgc   ,errcode=errcode)
    #endif
  else
    #ifdef DECOMPCASCADECNMOD
    call fio_read(18, "DecompCNParamsInst%cn_s1_cn    ",DecompCNParamsInst%cn_s1_cn    ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%cn_s2_cn    ",DecompCNParamsInst%cn_s2_cn    ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%cn_s3_cn    ",DecompCNParamsInst%cn_s3_cn    ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%cn_s4_cn    ",DecompCNParamsInst%cn_s4_cn    ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%np_s1_new_cn",DecompCNParamsInst%np_s1_new_cn,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%np_s2_new_cn",DecompCNParamsInst%np_s2_new_cn,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%np_s3_new_cn",DecompCNParamsInst%np_s3_new_cn,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%np_s4_new_cn",DecompCNParamsInst%np_s4_new_cn,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%cp_s1_new_cn",DecompCNParamsInst%cp_s1_new_cn,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%cp_s2_new_cn",DecompCNParamsInst%cp_s2_new_cn,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%cp_s3_new_cn",DecompCNParamsInst%cp_s3_new_cn,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%cp_s4_new_cn",DecompCNParamsInst%cp_s4_new_cn,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%rf_l1s1_cn  ",DecompCNParamsInst%rf_l1s1_cn  ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%rf_l2s2_cn  ",DecompCNParamsInst%rf_l2s2_cn  ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%rf_l3s3_cn  ",DecompCNParamsInst%rf_l3s3_cn  ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%rf_s1s2_cn  ",DecompCNParamsInst%rf_s1s2_cn  ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%rf_s2s3_cn  ",DecompCNParamsInst%rf_s2s3_cn  ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%rf_s3s4_cn  ",DecompCNParamsInst%rf_s3s4_cn  ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%cwd_fcel_cn ",DecompCNParamsInst%cwd_fcel_cn ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%cwd_flig_cn ",DecompCNParamsInst%cwd_flig_cn ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%k_l1_cn     ",DecompCNParamsInst%k_l1_cn     ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%k_l2_cn     ",DecompCNParamsInst%k_l2_cn     ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%k_l3_cn     ",DecompCNParamsInst%k_l3_cn     ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%k_s1_cn     ",DecompCNParamsInst%k_s1_cn     ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%k_s2_cn     ",DecompCNParamsInst%k_s2_cn     ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%k_s3_cn     ",DecompCNParamsInst%k_s3_cn     ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%k_s4_cn     ",DecompCNParamsInst%k_s4_cn     ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%k_frag_cn   ",DecompCNParamsInst%k_frag_cn   ,errcode=errcode)
    call fio_read(18, "DecompCNParamsInst%minpsi_cn   ",DecompCNParamsInst%minpsi_cn   ,errcode=errcode)
    #endif
  end if

    #ifdef SOILLITTVERTTRANSPMOD
    call fio_read(18, "SoilLittVertTranspParamsInst%som_diffus                ",SoilLittVertTranspParamsInst%som_diffus                ,errcode=errcode)
    call fio_read(18, "SoilLittVertTranspParamsInst%cryoturb_diffusion_k      ",SoilLittVertTranspParamsInst%cryoturb_diffusion_k      ,errcode=errcode)
    call fio_read(18, "SoilLittVertTranspParamsInst%max_altdepth_cryoturbation",SoilLittVertTranspParamsInst%max_altdepth_cryoturbation,errcode=errcode)
    #endif

    #ifdef GAPMORTALITYMOD
    call fio_read(18, "CNGapMortParamsInst%am    ", CNGapMortParamsInst%am    , errcode=errcode)
    call fio_read(18, "CNGapMortParamsInst%k_mort", CNGapMortParamsInst%k_mort, errcode=errcode)
    #endif

    #ifdef SURFACEALBEDOMOD
    call fio_read(18, "albsat ", albsat , errcode=errcode)
    call fio_read(18, "albdry ", albdry , errcode=errcode)
    call fio_read(18, "isoicol", isoicol, errcode=errcode)
    #endif

    #ifdef SOILLITTDECOMPMOD
    call fio_read(18, "CNDecompParamsInst%dnp", CNDecompParamsInst%dnp, errcode=errcode)
    #endif
  end if

    call fio_close(18)

  end subroutine read_constants

end module readConstants
