subroutine write_vars()
     use fileio_mod, only : fio_open, fio_close
     implicit none 
     integer :: fid 
     character(len=256) :: ofile = "output_vars.txt" 
     fid = 23 
     call fio_open(fid,ofile, 2) 
     
     !====================== canopystate_vars ======================!
     
     write (fid, "(A)") "canopystate_vars%frac_veg_nosno_patch" 
     write (fid, *) canopystate_vars%frac_veg_nosno_patch
     write (fid, "(A)") "canopystate_vars%frac_veg_nosno_alb_patch" 
     write (fid, *) canopystate_vars%frac_veg_nosno_alb_patch
     write (fid, "(A)") "canopystate_vars%tlai_patch" 
     write (fid, *) canopystate_vars%tlai_patch
     write (fid, "(A)") "canopystate_vars%tsai_patch" 
     write (fid, *) canopystate_vars%tsai_patch
     write (fid, "(A)") "canopystate_vars%elai_patch" 
     write (fid, *) canopystate_vars%elai_patch
     write (fid, "(A)") "canopystate_vars%esai_patch" 
     write (fid, *) canopystate_vars%esai_patch
     write (fid, "(A)") "canopystate_vars%elai_p_patch" 
     write (fid, *) canopystate_vars%elai_p_patch
     write (fid, "(A)") "canopystate_vars%laisun_patch" 
     write (fid, *) canopystate_vars%laisun_patch
     write (fid, "(A)") "canopystate_vars%laisha_patch" 
     write (fid, *) canopystate_vars%laisha_patch
     write (fid, "(A)") "canopystate_vars%laisun_z_patch" 
     write (fid, *) canopystate_vars%laisun_z_patch
     write (fid, "(A)") "canopystate_vars%laisha_z_patch" 
     write (fid, *) canopystate_vars%laisha_z_patch
     write (fid, "(A)") "canopystate_vars%mlaidiff_patch" 
     write (fid, *) canopystate_vars%mlaidiff_patch
     write (fid, "(A)") "canopystate_vars%annlai_patch" 
     write (fid, *) canopystate_vars%annlai_patch
     write (fid, "(A)") "canopystate_vars%htop_patch" 
     write (fid, *) canopystate_vars%htop_patch
     write (fid, "(A)") "canopystate_vars%hbot_patch" 
     write (fid, *) canopystate_vars%hbot_patch
     write (fid, "(A)") "canopystate_vars%displa_patch" 
     write (fid, *) canopystate_vars%displa_patch
     write (fid, "(A)") "canopystate_vars%fsun_patch" 
     write (fid, *) canopystate_vars%fsun_patch
     write (fid, "(A)") "canopystate_vars%fsun24_patch" 
     write (fid, *) canopystate_vars%fsun24_patch
     write (fid, "(A)") "canopystate_vars%fsun240_patch" 
     write (fid, *) canopystate_vars%fsun240_patch
     write (fid, "(A)") "canopystate_vars%alt_col" 
     write (fid, *) canopystate_vars%alt_col
     write (fid, "(A)") "canopystate_vars%alt_indx_col" 
     write (fid, *) canopystate_vars%alt_indx_col
     write (fid, "(A)") "canopystate_vars%altmax_col" 
     write (fid, *) canopystate_vars%altmax_col
     write (fid, "(A)") "canopystate_vars%altmax_lastyear_col" 
     write (fid, *) canopystate_vars%altmax_lastyear_col
     write (fid, "(A)") "canopystate_vars%altmax_indx_col" 
     write (fid, *) canopystate_vars%altmax_indx_col
     write (fid, "(A)") "canopystate_vars%altmax_lastyear_indx_col" 
     write (fid, *) canopystate_vars%altmax_lastyear_indx_col
     write (fid, "(A)") "canopystate_vars%dewmx_patch" 
     write (fid, *) canopystate_vars%dewmx_patch
     write (fid, "(A)") "canopystate_vars%dleaf_patch" 
     write (fid, *) canopystate_vars%dleaf_patch
     write (fid, "(A)") "canopystate_vars%lbl_rsc_h2o_patch" 
     write (fid, *) canopystate_vars%lbl_rsc_h2o_patch
     
     !====================== grc_pp ======================!
     
     write (fid, "(A)") "grc_pp%gindex" 
     write (fid, *) grc_pp%gindex
     write (fid, "(A)") "grc_pp%area" 
     write (fid, *) grc_pp%area
     write (fid, "(A)") "grc_pp%lat" 
     write (fid, *) grc_pp%lat
     write (fid, "(A)") "grc_pp%lon" 
     write (fid, *) grc_pp%lon
     write (fid, "(A)") "grc_pp%latdeg" 
     write (fid, *) grc_pp%latdeg
     write (fid, "(A)") "grc_pp%londeg" 
     write (fid, *) grc_pp%londeg
     write (fid, "(A)") "grc_pp%topi" 
     write (fid, *) grc_pp%topi
     write (fid, "(A)") "grc_pp%topf" 
     write (fid, *) grc_pp%topf
     write (fid, "(A)") "grc_pp%ntopounits" 
     write (fid, *) grc_pp%ntopounits
     write (fid, "(A)") "grc_pp%lndi" 
     write (fid, *) grc_pp%lndi
     write (fid, "(A)") "grc_pp%lndf" 
     write (fid, *) grc_pp%lndf
     write (fid, "(A)") "grc_pp%nlandunits" 
     write (fid, *) grc_pp%nlandunits
     write (fid, "(A)") "grc_pp%coli" 
     write (fid, *) grc_pp%coli
     write (fid, "(A)") "grc_pp%colf" 
     write (fid, *) grc_pp%colf
     write (fid, "(A)") "grc_pp%ncolumns" 
     write (fid, *) grc_pp%ncolumns
     write (fid, "(A)") "grc_pp%pfti" 
     write (fid, *) grc_pp%pfti
     write (fid, "(A)") "grc_pp%pftf" 
     write (fid, *) grc_pp%pftf
     write (fid, "(A)") "grc_pp%npfts" 
     write (fid, *) grc_pp%npfts
     write (fid, "(A)") "grc_pp%max_dayl" 
     write (fid, *) grc_pp%max_dayl
     write (fid, "(A)") "grc_pp%dayl" 
     write (fid, *) grc_pp%dayl
     write (fid, "(A)") "grc_pp%prev_dayl" 
     write (fid, *) grc_pp%prev_dayl
     write (fid, "(A)") "grc_pp%landunit_indices" 
     write (fid, *) grc_pp%landunit_indices
     
     !====================== top_as ======================!
     
     write (fid, "(A)") "top_as%tbot" 
     write (fid, *) top_as%tbot
     write (fid, "(A)") "top_as%thbot" 
     write (fid, *) top_as%thbot
     write (fid, "(A)") "top_as%pbot" 
     write (fid, *) top_as%pbot
     write (fid, "(A)") "top_as%rhobot" 
     write (fid, *) top_as%rhobot
     write (fid, "(A)") "top_as%qbot" 
     write (fid, *) top_as%qbot
     write (fid, "(A)") "top_as%rhbot" 
     write (fid, *) top_as%rhbot
     write (fid, "(A)") "top_as%ubot" 
     write (fid, *) top_as%ubot
     write (fid, "(A)") "top_as%vbot" 
     write (fid, *) top_as%vbot
     write (fid, "(A)") "top_as%windbot" 
     write (fid, *) top_as%windbot
     write (fid, "(A)") "top_as%zbot" 
     write (fid, *) top_as%zbot
     write (fid, "(A)") "top_as%po2bot" 
     write (fid, *) top_as%po2bot
     write (fid, "(A)") "top_as%pco2bot" 
     write (fid, *) top_as%pco2bot
     write (fid, "(A)") "top_as%pc13o2bot" 
     write (fid, *) top_as%pc13o2bot
     write (fid, "(A)") "top_as%pch4bot" 
     write (fid, *) top_as%pch4bot
     write (fid, "(A)") "top_as%rh24h" 
     write (fid, *) top_as%rh24h
     write (fid, "(A)") "top_as%wind24h" 
     write (fid, *) top_as%wind24h
     
     !====================== lun_pp ======================!
     
     write (fid, "(A)") "lun_pp%gridcell" 
     write (fid, *) lun_pp%gridcell
     write (fid, "(A)") "lun_pp%wtgcell" 
     write (fid, *) lun_pp%wtgcell
     write (fid, "(A)") "lun_pp%topounit" 
     write (fid, *) lun_pp%topounit
     write (fid, "(A)") "lun_pp%wttopounit" 
     write (fid, *) lun_pp%wttopounit
     write (fid, "(A)") "lun_pp%coli" 
     write (fid, *) lun_pp%coli
     write (fid, "(A)") "lun_pp%colf" 
     write (fid, *) lun_pp%colf
     write (fid, "(A)") "lun_pp%ncolumns" 
     write (fid, *) lun_pp%ncolumns
     write (fid, "(A)") "lun_pp%pfti" 
     write (fid, *) lun_pp%pfti
     write (fid, "(A)") "lun_pp%pftf" 
     write (fid, *) lun_pp%pftf
     write (fid, "(A)") "lun_pp%npfts" 
     write (fid, *) lun_pp%npfts
     write (fid, "(A)") "lun_pp%itype" 
     write (fid, *) lun_pp%itype
     write (fid, "(A)") "lun_pp%ifspecial" 
     write (fid, *) lun_pp%ifspecial
     write (fid, "(A)") "lun_pp%lakpoi" 
     write (fid, *) lun_pp%lakpoi
     write (fid, "(A)") "lun_pp%urbpoi" 
     write (fid, *) lun_pp%urbpoi
     write (fid, "(A)") "lun_pp%glcmecpoi" 
     write (fid, *) lun_pp%glcmecpoi
     write (fid, "(A)") "lun_pp%active" 
     write (fid, *) lun_pp%active
     write (fid, "(A)") "lun_pp%canyon_hwr" 
     write (fid, *) lun_pp%canyon_hwr
     write (fid, "(A)") "lun_pp%wtroad_perv" 
     write (fid, *) lun_pp%wtroad_perv
     write (fid, "(A)") "lun_pp%wtlunit_roof" 
     write (fid, *) lun_pp%wtlunit_roof
     write (fid, "(A)") "lun_pp%ht_roof" 
     write (fid, *) lun_pp%ht_roof
     write (fid, "(A)") "lun_pp%z_0_town" 
     write (fid, *) lun_pp%z_0_town
     write (fid, "(A)") "lun_pp%z_d_town" 
     write (fid, *) lun_pp%z_d_town
     
     !====================== col_pp ======================!
     
     write (fid, "(A)") "col_pp%gridcell" 
     write (fid, *) col_pp%gridcell
     write (fid, "(A)") "col_pp%wtgcell" 
     write (fid, *) col_pp%wtgcell
     write (fid, "(A)") "col_pp%topounit" 
     write (fid, *) col_pp%topounit
     write (fid, "(A)") "col_pp%wttopounit" 
     write (fid, *) col_pp%wttopounit
     write (fid, "(A)") "col_pp%landunit" 
     write (fid, *) col_pp%landunit
     write (fid, "(A)") "col_pp%wtlunit" 
     write (fid, *) col_pp%wtlunit
     write (fid, "(A)") "col_pp%pfti" 
     write (fid, *) col_pp%pfti
     write (fid, "(A)") "col_pp%pftf" 
     write (fid, *) col_pp%pftf
     write (fid, "(A)") "col_pp%npfts" 
     write (fid, *) col_pp%npfts
     write (fid, "(A)") "col_pp%itype" 
     write (fid, *) col_pp%itype
     write (fid, "(A)") "col_pp%active" 
     write (fid, *) col_pp%active
     write (fid, "(A)") "col_pp%glc_topo" 
     write (fid, *) col_pp%glc_topo
     write (fid, "(A)") "col_pp%micro_sigma" 
     write (fid, *) col_pp%micro_sigma
     write (fid, "(A)") "col_pp%n_melt" 
     write (fid, *) col_pp%n_melt
     write (fid, "(A)") "col_pp%topo_slope" 
     write (fid, *) col_pp%topo_slope
     write (fid, "(A)") "col_pp%topo_std" 
     write (fid, *) col_pp%topo_std
     write (fid, "(A)") "col_pp%nlevbed" 
     write (fid, *) col_pp%nlevbed
     write (fid, "(A)") "col_pp%zibed" 
     write (fid, *) col_pp%zibed
     write (fid, "(A)") "col_pp%snl" 
     write (fid, *) col_pp%snl
     write (fid, "(A)") "col_pp%dz" 
     write (fid, *) col_pp%dz
     write (fid, "(A)") "col_pp%z" 
     write (fid, *) col_pp%z
     write (fid, "(A)") "col_pp%zi" 
     write (fid, *) col_pp%zi
     write (fid, "(A)") "col_pp%zii" 
     write (fid, *) col_pp%zii
     write (fid, "(A)") "col_pp%dz_lake" 
     write (fid, *) col_pp%dz_lake
     write (fid, "(A)") "col_pp%z_lake" 
     write (fid, *) col_pp%z_lake
     write (fid, "(A)") "col_pp%lakedepth" 
     write (fid, *) col_pp%lakedepth
     write (fid, "(A)") "col_pp%hydrologically_active" 
     write (fid, *) col_pp%hydrologically_active
     
     !====================== col_es ======================!
     
     write (fid, "(A)") "col_es%t_soisno" 
     write (fid, *) col_es%t_soisno
     write (fid, "(A)") "col_es%t_ssbef" 
     write (fid, *) col_es%t_ssbef
     write (fid, "(A)") "col_es%t_h2osfc" 
     write (fid, *) col_es%t_h2osfc
     write (fid, "(A)") "col_es%t_h2osfc_bef" 
     write (fid, *) col_es%t_h2osfc_bef
     write (fid, "(A)") "col_es%t_soi10cm" 
     write (fid, *) col_es%t_soi10cm
     write (fid, "(A)") "col_es%t_soi17cm" 
     write (fid, *) col_es%t_soi17cm
     write (fid, "(A)") "col_es%t_grnd" 
     write (fid, *) col_es%t_grnd
     write (fid, "(A)") "col_es%t_lake" 
     write (fid, *) col_es%t_lake
     write (fid, "(A)") "col_es%t_grnd_r" 
     write (fid, *) col_es%t_grnd_r
     write (fid, "(A)") "col_es%t_grnd_u" 
     write (fid, *) col_es%t_grnd_u
     write (fid, "(A)") "col_es%snot_top" 
     write (fid, *) col_es%snot_top
     write (fid, "(A)") "col_es%dTdz_top" 
     write (fid, *) col_es%dTdz_top
     write (fid, "(A)") "col_es%thv" 
     write (fid, *) col_es%thv
     write (fid, "(A)") "col_es%hc_soi" 
     write (fid, *) col_es%hc_soi
     write (fid, "(A)") "col_es%hc_soisno" 
     write (fid, *) col_es%hc_soisno
     write (fid, "(A)") "col_es%emg" 
     write (fid, *) col_es%emg
     write (fid, "(A)") "col_es%fact" 
     write (fid, *) col_es%fact
     write (fid, "(A)") "col_es%c_h2osfc" 
     write (fid, *) col_es%c_h2osfc
     write (fid, "(A)") "col_es%t_nearsurf" 
     write (fid, *) col_es%t_nearsurf
     
     !====================== col_ef ======================!
     
     write (fid, "(A)") "col_ef%eflx_h2osfc_to_snow" 
     write (fid, *) col_ef%eflx_h2osfc_to_snow
     write (fid, "(A)") "col_ef%eflx_snomelt" 
     write (fid, *) col_ef%eflx_snomelt
     write (fid, "(A)") "col_ef%eflx_snomelt_r" 
     write (fid, *) col_ef%eflx_snomelt_r
     write (fid, "(A)") "col_ef%eflx_snomelt_u" 
     write (fid, *) col_ef%eflx_snomelt_u
     write (fid, "(A)") "col_ef%eflx_bot" 
     write (fid, *) col_ef%eflx_bot
     write (fid, "(A)") "col_ef%eflx_fgr12" 
     write (fid, *) col_ef%eflx_fgr12
     write (fid, "(A)") "col_ef%eflx_fgr" 
     write (fid, *) col_ef%eflx_fgr
     write (fid, "(A)") "col_ef%eflx_building_heat" 
     write (fid, *) col_ef%eflx_building_heat
     write (fid, "(A)") "col_ef%eflx_urban_ac" 
     write (fid, *) col_ef%eflx_urban_ac
     write (fid, "(A)") "col_ef%eflx_urban_heat" 
     write (fid, *) col_ef%eflx_urban_heat
     write (fid, "(A)") "col_ef%eflx_hs_h2osfc" 
     write (fid, *) col_ef%eflx_hs_h2osfc
     write (fid, "(A)") "col_ef%eflx_hs_top_snow" 
     write (fid, *) col_ef%eflx_hs_top_snow
     write (fid, "(A)") "col_ef%eflx_hs_soil" 
     write (fid, *) col_ef%eflx_hs_soil
     write (fid, "(A)") "col_ef%eflx_sabg_lyr" 
     write (fid, *) col_ef%eflx_sabg_lyr
     write (fid, "(A)") "col_ef%eflx_dhsdT" 
     write (fid, *) col_ef%eflx_dhsdT
     write (fid, "(A)") "col_ef%htvp" 
     write (fid, *) col_ef%htvp
     write (fid, "(A)") "col_ef%xmf" 
     write (fid, *) col_ef%xmf
     write (fid, "(A)") "col_ef%xmf_h2osfc" 
     write (fid, *) col_ef%xmf_h2osfc
     write (fid, "(A)") "col_ef%imelt" 
     write (fid, *) col_ef%imelt
     write (fid, "(A)") "col_ef%eflx_soil_grnd" 
     write (fid, *) col_ef%eflx_soil_grnd
     write (fid, "(A)") "col_ef%eflx_rnet_soil" 
     write (fid, *) col_ef%eflx_rnet_soil
     write (fid, "(A)") "col_ef%eflx_fgr0_soil" 
     write (fid, *) col_ef%eflx_fgr0_soil
     write (fid, "(A)") "col_ef%eflx_fgr0_snow" 
     write (fid, *) col_ef%eflx_fgr0_snow
     write (fid, "(A)") "col_ef%eflx_fgr0_h2osfc" 
     write (fid, *) col_ef%eflx_fgr0_h2osfc
     write (fid, "(A)") "col_ef%errsoi" 
     write (fid, *) col_ef%errsoi
     write (fid, "(A)") "col_ef%errseb" 
     write (fid, *) col_ef%errseb
     write (fid, "(A)") "col_ef%errsol" 
     write (fid, *) col_ef%errsol
     write (fid, "(A)") "col_ef%errlon" 
     write (fid, *) col_ef%errlon
     
     !====================== col_ws ======================!
     
     write (fid, "(A)") "col_ws%h2osoi_liq" 
     write (fid, *) col_ws%h2osoi_liq
     write (fid, "(A)") "col_ws%h2osoi_ice" 
     write (fid, *) col_ws%h2osoi_ice
     write (fid, "(A)") "col_ws%h2osoi_vol" 
     write (fid, *) col_ws%h2osoi_vol
     write (fid, "(A)") "col_ws%h2osfc" 
     write (fid, *) col_ws%h2osfc
     write (fid, "(A)") "col_ws%h2ocan" 
     write (fid, *) col_ws%h2ocan
     write (fid, "(A)") "col_ws%total_plant_stored_h2o" 
     write (fid, *) col_ws%total_plant_stored_h2o
     write (fid, "(A)") "col_ws%h2osoi_liqvol" 
     write (fid, *) col_ws%h2osoi_liqvol
     write (fid, "(A)") "col_ws%h2osoi_icevol" 
     write (fid, *) col_ws%h2osoi_icevol
     write (fid, "(A)") "col_ws%h2osoi_liq_old" 
     write (fid, *) col_ws%h2osoi_liq_old
     write (fid, "(A)") "col_ws%h2osoi_ice_old" 
     write (fid, *) col_ws%h2osoi_ice_old
     write (fid, "(A)") "col_ws%bw" 
     write (fid, *) col_ws%bw
     write (fid, "(A)") "col_ws%smp_l" 
     write (fid, *) col_ws%smp_l
     write (fid, "(A)") "col_ws%soilp" 
     write (fid, *) col_ws%soilp
     write (fid, "(A)") "col_ws%swe_old" 
     write (fid, *) col_ws%swe_old
     write (fid, "(A)") "col_ws%snw_rds" 
     write (fid, *) col_ws%snw_rds
     write (fid, "(A)") "col_ws%air_vol" 
     write (fid, *) col_ws%air_vol
     write (fid, "(A)") "col_ws%qg_snow" 
     write (fid, *) col_ws%qg_snow
     write (fid, "(A)") "col_ws%qg_soil" 
     write (fid, *) col_ws%qg_soil
     write (fid, "(A)") "col_ws%qg_h2osfc" 
     write (fid, *) col_ws%qg_h2osfc
     write (fid, "(A)") "col_ws%qg" 
     write (fid, *) col_ws%qg
     write (fid, "(A)") "col_ws%dqgdT" 
     write (fid, *) col_ws%dqgdT
     write (fid, "(A)") "col_ws%h2osoi_liqice_10cm" 
     write (fid, *) col_ws%h2osoi_liqice_10cm
     write (fid, "(A)") "col_ws%h2osno" 
     write (fid, *) col_ws%h2osno
     write (fid, "(A)") "col_ws%h2osno_old" 
     write (fid, *) col_ws%h2osno_old
     write (fid, "(A)") "col_ws%h2osno_top" 
     write (fid, *) col_ws%h2osno_top
     write (fid, "(A)") "col_ws%sno_liq_top" 
     write (fid, *) col_ws%sno_liq_top
     write (fid, "(A)") "col_ws%snowice" 
     write (fid, *) col_ws%snowice
     write (fid, "(A)") "col_ws%snowliq" 
     write (fid, *) col_ws%snowliq
     write (fid, "(A)") "col_ws%int_snow" 
     write (fid, *) col_ws%int_snow
     write (fid, "(A)") "col_ws%snow_depth" 
     write (fid, *) col_ws%snow_depth
     write (fid, "(A)") "col_ws%snowdp" 
     write (fid, *) col_ws%snowdp
     write (fid, "(A)") "col_ws%snow_persistence" 
     write (fid, *) col_ws%snow_persistence
     write (fid, "(A)") "col_ws%snw_rds_top" 
     write (fid, *) col_ws%snw_rds_top
     write (fid, "(A)") "col_ws%do_capsnow" 
     write (fid, *) col_ws%do_capsnow
     write (fid, "(A)") "col_ws%frac_sno" 
     write (fid, *) col_ws%frac_sno
     write (fid, "(A)") "col_ws%frac_sno_eff" 
     write (fid, *) col_ws%frac_sno_eff
     write (fid, "(A)") "col_ws%frac_iceold" 
     write (fid, *) col_ws%frac_iceold
     write (fid, "(A)") "col_ws%frac_h2osfc" 
     write (fid, *) col_ws%frac_h2osfc
     write (fid, "(A)") "col_ws%wf" 
     write (fid, *) col_ws%wf
     write (fid, "(A)") "col_ws%wf2" 
     write (fid, *) col_ws%wf2
     write (fid, "(A)") "col_ws%finundated" 
     write (fid, *) col_ws%finundated
     write (fid, "(A)") "col_ws%begwb" 
     write (fid, *) col_ws%begwb
     write (fid, "(A)") "col_ws%endwb" 
     write (fid, *) col_ws%endwb
     write (fid, "(A)") "col_ws%errh2o" 
     write (fid, *) col_ws%errh2o
     write (fid, "(A)") "col_ws%errh2osno" 
     write (fid, *) col_ws%errh2osno
     write (fid, "(A)") "col_ws%h2osoi_liq_depth_intg" 
     write (fid, *) col_ws%h2osoi_liq_depth_intg
     write (fid, "(A)") "col_ws%h2osoi_ice_depth_intg" 
     write (fid, *) col_ws%h2osoi_ice_depth_intg
     write (fid, "(A)") "col_ws%vsfm_fliq_col_1d" 
     write (fid, *) col_ws%vsfm_fliq_col_1d
     write (fid, "(A)") "col_ws%vsfm_sat_col_1d" 
     write (fid, *) col_ws%vsfm_sat_col_1d
     write (fid, "(A)") "col_ws%vsfm_mass_col_1d" 
     write (fid, *) col_ws%vsfm_mass_col_1d
     write (fid, "(A)") "col_ws%vsfm_smpl_col_1d" 
     write (fid, *) col_ws%vsfm_smpl_col_1d
     write (fid, "(A)") "col_ws%vsfm_soilp_col_1d" 
     write (fid, *) col_ws%vsfm_soilp_col_1d
     
     !====================== col_wf ======================!
     
     write (fid, "(A)") "col_wf%qflx_prec_grnd" 
     write (fid, *) col_wf%qflx_prec_grnd
     write (fid, "(A)") "col_wf%qflx_rain_grnd" 
     write (fid, *) col_wf%qflx_rain_grnd
     write (fid, "(A)") "col_wf%qflx_snow_grnd" 
     write (fid, *) col_wf%qflx_snow_grnd
     write (fid, "(A)") "col_wf%qflx_sub_snow" 
     write (fid, *) col_wf%qflx_sub_snow
     write (fid, "(A)") "col_wf%qflx_sub_snow_vol" 
     write (fid, *) col_wf%qflx_sub_snow_vol
     write (fid, "(A)") "col_wf%qflx_evap_soi" 
     write (fid, *) col_wf%qflx_evap_soi
     write (fid, "(A)") "col_wf%qflx_evap_veg" 
     write (fid, *) col_wf%qflx_evap_veg
     write (fid, "(A)") "col_wf%qflx_evap_can" 
     write (fid, *) col_wf%qflx_evap_can
     write (fid, "(A)") "col_wf%qflx_evap_tot" 
     write (fid, *) col_wf%qflx_evap_tot
     write (fid, "(A)") "col_wf%qflx_evap_grnd" 
     write (fid, *) col_wf%qflx_evap_grnd
     write (fid, "(A)") "col_wf%qflx_snwcp_liq" 
     write (fid, *) col_wf%qflx_snwcp_liq
     write (fid, "(A)") "col_wf%qflx_snwcp_ice" 
     write (fid, *) col_wf%qflx_snwcp_ice
     write (fid, "(A)") "col_wf%qflx_tran_veg" 
     write (fid, *) col_wf%qflx_tran_veg
     write (fid, "(A)") "col_wf%qflx_dew_snow" 
     write (fid, *) col_wf%qflx_dew_snow
     write (fid, "(A)") "col_wf%qflx_dew_grnd" 
     write (fid, *) col_wf%qflx_dew_grnd
     write (fid, "(A)") "col_wf%qflx_prec_intr" 
     write (fid, *) col_wf%qflx_prec_intr
     write (fid, "(A)") "col_wf%qflx_ev_snow" 
     write (fid, *) col_wf%qflx_ev_snow
     write (fid, "(A)") "col_wf%qflx_ev_soil" 
     write (fid, *) col_wf%qflx_ev_soil
     write (fid, "(A)") "col_wf%qflx_ev_h2osfc" 
     write (fid, *) col_wf%qflx_ev_h2osfc
     write (fid, "(A)") "col_wf%qflx_gross_evap_soil" 
     write (fid, *) col_wf%qflx_gross_evap_soil
     write (fid, "(A)") "col_wf%qflx_gross_infl_soil" 
     write (fid, *) col_wf%qflx_gross_infl_soil
     write (fid, "(A)") "col_wf%qflx_adv" 
     write (fid, *) col_wf%qflx_adv
     write (fid, "(A)") "col_wf%qflx_rootsoi" 
     write (fid, *) col_wf%qflx_rootsoi
     write (fid, "(A)") "col_wf%dwb" 
     write (fid, *) col_wf%dwb
     write (fid, "(A)") "col_wf%qflx_infl" 
     write (fid, *) col_wf%qflx_infl
     write (fid, "(A)") "col_wf%qflx_surf" 
     write (fid, *) col_wf%qflx_surf
     write (fid, "(A)") "col_wf%qflx_drain" 
     write (fid, *) col_wf%qflx_drain
     write (fid, "(A)") "col_wf%qflx_totdrain" 
     write (fid, *) col_wf%qflx_totdrain
     write (fid, "(A)") "col_wf%qflx_top_soil" 
     write (fid, *) col_wf%qflx_top_soil
     write (fid, "(A)") "col_wf%qflx_h2osfc_to_ice" 
     write (fid, *) col_wf%qflx_h2osfc_to_ice
     write (fid, "(A)") "col_wf%qflx_h2osfc_surf" 
     write (fid, *) col_wf%qflx_h2osfc_surf
     write (fid, "(A)") "col_wf%qflx_snow_h2osfc" 
     write (fid, *) col_wf%qflx_snow_h2osfc
     write (fid, "(A)") "col_wf%qflx_drain_perched" 
     write (fid, *) col_wf%qflx_drain_perched
     write (fid, "(A)") "col_wf%qflx_deficit" 
     write (fid, *) col_wf%qflx_deficit
     write (fid, "(A)") "col_wf%qflx_floodc" 
     write (fid, *) col_wf%qflx_floodc
     write (fid, "(A)") "col_wf%qflx_sl_top_soil" 
     write (fid, *) col_wf%qflx_sl_top_soil
     write (fid, "(A)") "col_wf%qflx_snomelt" 
     write (fid, *) col_wf%qflx_snomelt
     write (fid, "(A)") "col_wf%qflx_snow_melt" 
     write (fid, *) col_wf%qflx_snow_melt
     write (fid, "(A)") "col_wf%qflx_qrgwl" 
     write (fid, *) col_wf%qflx_qrgwl
     write (fid, "(A)") "col_wf%qflx_runoff" 
     write (fid, *) col_wf%qflx_runoff
     write (fid, "(A)") "col_wf%qflx_runoff_r" 
     write (fid, *) col_wf%qflx_runoff_r
     write (fid, "(A)") "col_wf%qflx_runoff_u" 
     write (fid, *) col_wf%qflx_runoff_u
     write (fid, "(A)") "col_wf%qflx_rsub_sat" 
     write (fid, *) col_wf%qflx_rsub_sat
     write (fid, "(A)") "col_wf%qflx_snofrz_lyr" 
     write (fid, *) col_wf%qflx_snofrz_lyr
     write (fid, "(A)") "col_wf%qflx_snofrz" 
     write (fid, *) col_wf%qflx_snofrz
     write (fid, "(A)") "col_wf%qflx_glcice" 
     write (fid, *) col_wf%qflx_glcice
     write (fid, "(A)") "col_wf%qflx_glcice_frz" 
     write (fid, *) col_wf%qflx_glcice_frz
     write (fid, "(A)") "col_wf%qflx_glcice_melt" 
     write (fid, *) col_wf%qflx_glcice_melt
     write (fid, "(A)") "col_wf%qflx_drain_vr" 
     write (fid, *) col_wf%qflx_drain_vr
     write (fid, "(A)") "col_wf%qflx_h2osfc2topsoi" 
     write (fid, *) col_wf%qflx_h2osfc2topsoi
     write (fid, "(A)") "col_wf%qflx_snow2topsoi" 
     write (fid, *) col_wf%qflx_snow2topsoi
     write (fid, "(A)") "col_wf%qflx_lateral" 
     write (fid, *) col_wf%qflx_lateral
     write (fid, "(A)") "col_wf%snow_sources" 
     write (fid, *) col_wf%snow_sources
     write (fid, "(A)") "col_wf%snow_sinks" 
     write (fid, *) col_wf%snow_sinks
     write (fid, "(A)") "col_wf%qflx_irrig" 
     write (fid, *) col_wf%qflx_irrig
     write (fid, "(A)") "col_wf%mflx_infl_1d" 
     write (fid, *) col_wf%mflx_infl_1d
     write (fid, "(A)") "col_wf%mflx_dew_1d" 
     write (fid, *) col_wf%mflx_dew_1d
     write (fid, "(A)") "col_wf%mflx_et_1d" 
     write (fid, *) col_wf%mflx_et_1d
     write (fid, "(A)") "col_wf%mflx_drain_1d" 
     write (fid, *) col_wf%mflx_drain_1d
     write (fid, "(A)") "col_wf%mflx_drain_perched_1d" 
     write (fid, *) col_wf%mflx_drain_perched_1d
     write (fid, "(A)") "col_wf%mflx_snowlyr_1d" 
     write (fid, *) col_wf%mflx_snowlyr_1d
     write (fid, "(A)") "col_wf%mflx_sub_snow_1d" 
     write (fid, *) col_wf%mflx_sub_snow_1d
     write (fid, "(A)") "col_wf%mflx_neg_snow_1d" 
     write (fid, *) col_wf%mflx_neg_snow_1d
     write (fid, "(A)") "col_wf%mflx_snowlyr" 
     write (fid, *) col_wf%mflx_snowlyr
     write (fid, "(A)") "col_wf%mflx_infl" 
     write (fid, *) col_wf%mflx_infl
     write (fid, "(A)") "col_wf%mflx_dew" 
     write (fid, *) col_wf%mflx_dew
     write (fid, "(A)") "col_wf%mflx_snowlyr_disp" 
     write (fid, *) col_wf%mflx_snowlyr_disp
     write (fid, "(A)") "col_wf%mflx_sub_snow" 
     write (fid, *) col_wf%mflx_sub_snow
     write (fid, "(A)") "col_wf%mflx_et" 
     write (fid, *) col_wf%mflx_et
     write (fid, "(A)") "col_wf%mflx_drain" 
     write (fid, *) col_wf%mflx_drain
     write (fid, "(A)") "col_wf%mflx_recharge" 
     write (fid, *) col_wf%mflx_recharge
     
     !====================== veg_pp ======================!
     
     write (fid, "(A)") "veg_pp%gridcell" 
     write (fid, *) veg_pp%gridcell
     write (fid, "(A)") "veg_pp%wtgcell" 
     write (fid, *) veg_pp%wtgcell
     write (fid, "(A)") "veg_pp%topounit" 
     write (fid, *) veg_pp%topounit
     write (fid, "(A)") "veg_pp%wttopounit" 
     write (fid, *) veg_pp%wttopounit
     write (fid, "(A)") "veg_pp%landunit" 
     write (fid, *) veg_pp%landunit
     write (fid, "(A)") "veg_pp%wtlunit" 
     write (fid, *) veg_pp%wtlunit
     write (fid, "(A)") "veg_pp%column" 
     write (fid, *) veg_pp%column
     write (fid, "(A)") "veg_pp%wtcol" 
     write (fid, *) veg_pp%wtcol
     write (fid, "(A)") "veg_pp%itype" 
     write (fid, *) veg_pp%itype
     write (fid, "(A)") "veg_pp%mxy" 
     write (fid, *) veg_pp%mxy
     write (fid, "(A)") "veg_pp%active" 
     write (fid, *) veg_pp%active
     write (fid, "(A)") "veg_pp%is_veg" 
     write (fid, *) veg_pp%is_veg
     write (fid, "(A)") "veg_pp%is_bareground" 
     write (fid, *) veg_pp%is_bareground
     write (fid, "(A)") "veg_pp%wt_ed" 
     write (fid, *) veg_pp%wt_ed
     write (fid, "(A)") "veg_pp%is_fates" 
     write (fid, *) veg_pp%is_fates
     
     !====================== veg_es ======================!
     
     write (fid, "(A)") "veg_es%t_veg" 
     write (fid, *) veg_es%t_veg
     write (fid, "(A)") "veg_es%t_ref2m" 
     write (fid, *) veg_es%t_ref2m
     write (fid, "(A)") "veg_es%t_ref2m_r" 
     write (fid, *) veg_es%t_ref2m_r
     write (fid, "(A)") "veg_es%t_ref2m_u" 
     write (fid, *) veg_es%t_ref2m_u
     write (fid, "(A)") "veg_es%t_a10" 
     write (fid, *) veg_es%t_a10
     write (fid, "(A)") "veg_es%t_a10min" 
     write (fid, *) veg_es%t_a10min
     write (fid, "(A)") "veg_es%t_a5min" 
     write (fid, *) veg_es%t_a5min
     write (fid, "(A)") "veg_es%t_ref2m_min" 
     write (fid, *) veg_es%t_ref2m_min
     write (fid, "(A)") "veg_es%t_ref2m_min_r" 
     write (fid, *) veg_es%t_ref2m_min_r
     write (fid, "(A)") "veg_es%t_ref2m_min_u" 
     write (fid, *) veg_es%t_ref2m_min_u
     write (fid, "(A)") "veg_es%t_ref2m_max" 
     write (fid, *) veg_es%t_ref2m_max
     write (fid, "(A)") "veg_es%t_ref2m_max_r" 
     write (fid, *) veg_es%t_ref2m_max_r
     write (fid, "(A)") "veg_es%t_ref2m_max_u" 
     write (fid, *) veg_es%t_ref2m_max_u
     write (fid, "(A)") "veg_es%t_ref2m_min_inst" 
     write (fid, *) veg_es%t_ref2m_min_inst
     write (fid, "(A)") "veg_es%t_ref2m_min_inst_r" 
     write (fid, *) veg_es%t_ref2m_min_inst_r
     write (fid, "(A)") "veg_es%t_ref2m_min_inst_u" 
     write (fid, *) veg_es%t_ref2m_min_inst_u
     write (fid, "(A)") "veg_es%t_ref2m_max_inst" 
     write (fid, *) veg_es%t_ref2m_max_inst
     write (fid, "(A)") "veg_es%t_ref2m_max_inst_r" 
     write (fid, *) veg_es%t_ref2m_max_inst_r
     write (fid, "(A)") "veg_es%t_ref2m_max_inst_u" 
     write (fid, *) veg_es%t_ref2m_max_inst_u
     write (fid, "(A)") "veg_es%t_veg24" 
     write (fid, *) veg_es%t_veg24
     write (fid, "(A)") "veg_es%t_veg240" 
     write (fid, *) veg_es%t_veg240
     write (fid, "(A)") "veg_es%gdd0" 
     write (fid, *) veg_es%gdd0
     write (fid, "(A)") "veg_es%gdd8" 
     write (fid, *) veg_es%gdd8
     write (fid, "(A)") "veg_es%gdd10" 
     write (fid, *) veg_es%gdd10
     write (fid, "(A)") "veg_es%gdd020" 
     write (fid, *) veg_es%gdd020
     write (fid, "(A)") "veg_es%gdd820" 
     write (fid, *) veg_es%gdd820
     write (fid, "(A)") "veg_es%gdd1020" 
     write (fid, *) veg_es%gdd1020
     write (fid, "(A)") "veg_es%thm" 
     write (fid, *) veg_es%thm
     write (fid, "(A)") "veg_es%emv" 
     write (fid, *) veg_es%emv
     
     !====================== veg_ef ======================!
     
     write (fid, "(A)") "veg_ef%eflx_sh_grnd" 
     write (fid, *) veg_ef%eflx_sh_grnd
     write (fid, "(A)") "veg_ef%eflx_sh_veg" 
     write (fid, *) veg_ef%eflx_sh_veg
     write (fid, "(A)") "veg_ef%eflx_sh_snow" 
     write (fid, *) veg_ef%eflx_sh_snow
     write (fid, "(A)") "veg_ef%eflx_sh_soil" 
     write (fid, *) veg_ef%eflx_sh_soil
     write (fid, "(A)") "veg_ef%eflx_sh_h2osfc" 
     write (fid, *) veg_ef%eflx_sh_h2osfc
     write (fid, "(A)") "veg_ef%eflx_sh_tot" 
     write (fid, *) veg_ef%eflx_sh_tot
     write (fid, "(A)") "veg_ef%eflx_sh_tot_u" 
     write (fid, *) veg_ef%eflx_sh_tot_u
     write (fid, "(A)") "veg_ef%eflx_sh_tot_r" 
     write (fid, *) veg_ef%eflx_sh_tot_r
     write (fid, "(A)") "veg_ef%eflx_lh_tot" 
     write (fid, *) veg_ef%eflx_lh_tot
     write (fid, "(A)") "veg_ef%eflx_lh_tot_u" 
     write (fid, *) veg_ef%eflx_lh_tot_u
     write (fid, "(A)") "veg_ef%eflx_lh_tot_r" 
     write (fid, *) veg_ef%eflx_lh_tot_r
     write (fid, "(A)") "veg_ef%eflx_lh_vegt" 
     write (fid, *) veg_ef%eflx_lh_vegt
     write (fid, "(A)") "veg_ef%eflx_lh_vege" 
     write (fid, *) veg_ef%eflx_lh_vege
     write (fid, "(A)") "veg_ef%eflx_lh_grnd" 
     write (fid, *) veg_ef%eflx_lh_grnd
     write (fid, "(A)") "veg_ef%eflx_soil_grnd" 
     write (fid, *) veg_ef%eflx_soil_grnd
     write (fid, "(A)") "veg_ef%eflx_soil_grnd_u" 
     write (fid, *) veg_ef%eflx_soil_grnd_u
     write (fid, "(A)") "veg_ef%eflx_soil_grnd_r" 
     write (fid, *) veg_ef%eflx_soil_grnd_r
     write (fid, "(A)") "veg_ef%eflx_lwrad_net" 
     write (fid, *) veg_ef%eflx_lwrad_net
     write (fid, "(A)") "veg_ef%eflx_lwrad_net_r" 
     write (fid, *) veg_ef%eflx_lwrad_net_r
     write (fid, "(A)") "veg_ef%eflx_lwrad_net_u" 
     write (fid, *) veg_ef%eflx_lwrad_net_u
     write (fid, "(A)") "veg_ef%eflx_lwrad_out" 
     write (fid, *) veg_ef%eflx_lwrad_out
     write (fid, "(A)") "veg_ef%eflx_lwrad_out_r" 
     write (fid, *) veg_ef%eflx_lwrad_out_r
     write (fid, "(A)") "veg_ef%eflx_lwrad_out_u" 
     write (fid, *) veg_ef%eflx_lwrad_out_u
     write (fid, "(A)") "veg_ef%eflx_gnet" 
     write (fid, *) veg_ef%eflx_gnet
     write (fid, "(A)") "veg_ef%eflx_grnd_lake" 
     write (fid, *) veg_ef%eflx_grnd_lake
     write (fid, "(A)") "veg_ef%eflx_anthro" 
     write (fid, *) veg_ef%eflx_anthro
     write (fid, "(A)") "veg_ef%eflx_traffic" 
     write (fid, *) veg_ef%eflx_traffic
     write (fid, "(A)") "veg_ef%eflx_wasteheat" 
     write (fid, *) veg_ef%eflx_wasteheat
     write (fid, "(A)") "veg_ef%eflx_heat_from_ac" 
     write (fid, *) veg_ef%eflx_heat_from_ac
     write (fid, "(A)") "veg_ef%dlrad" 
     write (fid, *) veg_ef%dlrad
     write (fid, "(A)") "veg_ef%ulrad" 
     write (fid, *) veg_ef%ulrad
     write (fid, "(A)") "veg_ef%taux" 
     write (fid, *) veg_ef%taux
     write (fid, "(A)") "veg_ef%tauy" 
     write (fid, *) veg_ef%tauy
     write (fid, "(A)") "veg_ef%dgnetdT" 
     write (fid, *) veg_ef%dgnetdT
     write (fid, "(A)") "veg_ef%netrad" 
     write (fid, *) veg_ef%netrad
     write (fid, "(A)") "veg_ef%cgrnd" 
     write (fid, *) veg_ef%cgrnd
     write (fid, "(A)") "veg_ef%cgrndl" 
     write (fid, *) veg_ef%cgrndl
     write (fid, "(A)") "veg_ef%cgrnds" 
     write (fid, *) veg_ef%cgrnds
     write (fid, "(A)") "veg_ef%errsoi" 
     write (fid, *) veg_ef%errsoi
     write (fid, "(A)") "veg_ef%errseb" 
     write (fid, *) veg_ef%errseb
     write (fid, "(A)") "veg_ef%errsol" 
     write (fid, *) veg_ef%errsol
     write (fid, "(A)") "veg_ef%errlon" 
     write (fid, *) veg_ef%errlon
     
     !====================== photosyns_vars ======================!
     
     write (fid, "(A)") "photosyns_vars%c3flag_patch" 
     write (fid, *) photosyns_vars%c3flag_patch
     write (fid, "(A)") "photosyns_vars%cp_patch" 
     write (fid, *) photosyns_vars%cp_patch
     write (fid, "(A)") "photosyns_vars%kc_patch" 
     write (fid, *) photosyns_vars%kc_patch
     write (fid, "(A)") "photosyns_vars%ko_patch" 
     write (fid, *) photosyns_vars%ko_patch
     write (fid, "(A)") "photosyns_vars%qe_patch" 
     write (fid, *) photosyns_vars%qe_patch
     write (fid, "(A)") "photosyns_vars%tpu_z_patch" 
     write (fid, *) photosyns_vars%tpu_z_patch
     write (fid, "(A)") "photosyns_vars%kp_z_patch" 
     write (fid, *) photosyns_vars%kp_z_patch
     write (fid, "(A)") "photosyns_vars%theta_cj_patch" 
     write (fid, *) photosyns_vars%theta_cj_patch
     write (fid, "(A)") "photosyns_vars%bbb_patch" 
     write (fid, *) photosyns_vars%bbb_patch
     write (fid, "(A)") "photosyns_vars%mbb_patch" 
     write (fid, *) photosyns_vars%mbb_patch
     write (fid, "(A)") "photosyns_vars%gs_mol_patch" 
     write (fid, *) photosyns_vars%gs_mol_patch
     write (fid, "(A)") "photosyns_vars%gb_mol_patch" 
     write (fid, *) photosyns_vars%gb_mol_patch
     write (fid, "(A)") "photosyns_vars%rh_leaf_patch" 
     write (fid, *) photosyns_vars%rh_leaf_patch
     write (fid, "(A)") "photosyns_vars%alphapsnsun_patch" 
     write (fid, *) photosyns_vars%alphapsnsun_patch
     write (fid, "(A)") "photosyns_vars%alphapsnsha_patch" 
     write (fid, *) photosyns_vars%alphapsnsha_patch
     write (fid, "(A)") "photosyns_vars%psnsun_patch" 
     write (fid, *) photosyns_vars%psnsun_patch
     write (fid, "(A)") "photosyns_vars%psnsha_patch" 
     write (fid, *) photosyns_vars%psnsha_patch
     write (fid, "(A)") "photosyns_vars%psnsun_z_patch" 
     write (fid, *) photosyns_vars%psnsun_z_patch
     write (fid, "(A)") "photosyns_vars%psnsha_z_patch" 
     write (fid, *) photosyns_vars%psnsha_z_patch
     write (fid, "(A)") "photosyns_vars%psnsun_wc_patch" 
     write (fid, *) photosyns_vars%psnsun_wc_patch
     write (fid, "(A)") "photosyns_vars%psnsha_wc_patch" 
     write (fid, *) photosyns_vars%psnsha_wc_patch
     write (fid, "(A)") "photosyns_vars%psnsun_wj_patch" 
     write (fid, *) photosyns_vars%psnsun_wj_patch
     write (fid, "(A)") "photosyns_vars%psnsha_wj_patch" 
     write (fid, *) photosyns_vars%psnsha_wj_patch
     write (fid, "(A)") "photosyns_vars%psnsun_wp_patch" 
     write (fid, *) photosyns_vars%psnsun_wp_patch
     write (fid, "(A)") "photosyns_vars%psnsha_wp_patch" 
     write (fid, *) photosyns_vars%psnsha_wp_patch
     write (fid, "(A)") "photosyns_vars%fpsn_patch" 
     write (fid, *) photosyns_vars%fpsn_patch
     write (fid, "(A)") "photosyns_vars%fpsn_wc_patch" 
     write (fid, *) photosyns_vars%fpsn_wc_patch
     write (fid, "(A)") "photosyns_vars%fpsn_wj_patch" 
     write (fid, *) photosyns_vars%fpsn_wj_patch
     write (fid, "(A)") "photosyns_vars%fpsn_wp_patch" 
     write (fid, *) photosyns_vars%fpsn_wp_patch
     write (fid, "(A)") "photosyns_vars%lmrsun_patch" 
     write (fid, *) photosyns_vars%lmrsun_patch
     write (fid, "(A)") "photosyns_vars%lmrsha_patch" 
     write (fid, *) photosyns_vars%lmrsha_patch
     write (fid, "(A)") "photosyns_vars%lmrsun_z_patch" 
     write (fid, *) photosyns_vars%lmrsun_z_patch
     write (fid, "(A)") "photosyns_vars%lmrsha_z_patch" 
     write (fid, *) photosyns_vars%lmrsha_z_patch
     write (fid, "(A)") "photosyns_vars%cisun_z_patch" 
     write (fid, *) photosyns_vars%cisun_z_patch
     write (fid, "(A)") "photosyns_vars%cisha_z_patch" 
     write (fid, *) photosyns_vars%cisha_z_patch
     write (fid, "(A)") "photosyns_vars%rssun_z_patch" 
     write (fid, *) photosyns_vars%rssun_z_patch
     write (fid, "(A)") "photosyns_vars%rssha_z_patch" 
     write (fid, *) photosyns_vars%rssha_z_patch
     write (fid, "(A)") "photosyns_vars%rssun_patch" 
     write (fid, *) photosyns_vars%rssun_patch
     write (fid, "(A)") "photosyns_vars%rssha_patch" 
     write (fid, *) photosyns_vars%rssha_patch
     write (fid, "(A)") "photosyns_vars%psncanopy_patch" 
     write (fid, *) photosyns_vars%psncanopy_patch
     write (fid, "(A)") "photosyns_vars%lmrcanopy_patch" 
     write (fid, *) photosyns_vars%lmrcanopy_patch
     
     !====================== frictionvel_vars ======================!
     
     write (fid, "(A)") "frictionvel_vars%forc_hgt_u_patch" 
     write (fid, *) frictionvel_vars%forc_hgt_u_patch
     write (fid, "(A)") "frictionvel_vars%forc_hgt_t_patch" 
     write (fid, *) frictionvel_vars%forc_hgt_t_patch
     write (fid, "(A)") "frictionvel_vars%forc_hgt_q_patch" 
     write (fid, *) frictionvel_vars%forc_hgt_q_patch
     write (fid, "(A)") "frictionvel_vars%u10_patch" 
     write (fid, *) frictionvel_vars%u10_patch
     write (fid, "(A)") "frictionvel_vars%u10_clm_patch" 
     write (fid, *) frictionvel_vars%u10_clm_patch
     write (fid, "(A)") "frictionvel_vars%va_patch" 
     write (fid, *) frictionvel_vars%va_patch
     write (fid, "(A)") "frictionvel_vars%vds_patch" 
     write (fid, *) frictionvel_vars%vds_patch
     write (fid, "(A)") "frictionvel_vars%fv_patch" 
     write (fid, *) frictionvel_vars%fv_patch
     write (fid, "(A)") "frictionvel_vars%rb1_patch" 
     write (fid, *) frictionvel_vars%rb1_patch
     write (fid, "(A)") "frictionvel_vars%ram1_patch" 
     write (fid, *) frictionvel_vars%ram1_patch
     write (fid, "(A)") "frictionvel_vars%z0m_patch" 
     write (fid, *) frictionvel_vars%z0m_patch
     write (fid, "(A)") "frictionvel_vars%z0mv_patch" 
     write (fid, *) frictionvel_vars%z0mv_patch
     write (fid, "(A)") "frictionvel_vars%z0hv_patch" 
     write (fid, *) frictionvel_vars%z0hv_patch
     write (fid, "(A)") "frictionvel_vars%z0qv_patch" 
     write (fid, *) frictionvel_vars%z0qv_patch
     write (fid, "(A)") "frictionvel_vars%z0mg_col" 
     write (fid, *) frictionvel_vars%z0mg_col
     write (fid, "(A)") "frictionvel_vars%z0hg_col" 
     write (fid, *) frictionvel_vars%z0hg_col
     write (fid, "(A)") "frictionvel_vars%z0qg_col" 
     write (fid, *) frictionvel_vars%z0qg_col
     
     !====================== atm2lnd_vars ======================!
     
     write (fid, "(A)") "atm2lnd_vars%forc_hdm" 
     write (fid, *) atm2lnd_vars%forc_hdm
     write (fid, "(A)") "atm2lnd_vars%forc_lnfm" 
     write (fid, *) atm2lnd_vars%forc_lnfm
     write (fid, "(A)") "atm2lnd_vars%forc_u_grc" 
     write (fid, *) atm2lnd_vars%forc_u_grc
     write (fid, "(A)") "atm2lnd_vars%forc_v_grc" 
     write (fid, *) atm2lnd_vars%forc_v_grc
     write (fid, "(A)") "atm2lnd_vars%forc_wind_grc" 
     write (fid, *) atm2lnd_vars%forc_wind_grc
     write (fid, "(A)") "atm2lnd_vars%forc_hgt_grc" 
     write (fid, *) atm2lnd_vars%forc_hgt_grc
     write (fid, "(A)") "atm2lnd_vars%forc_hgt_u_grc" 
     write (fid, *) atm2lnd_vars%forc_hgt_u_grc
     write (fid, "(A)") "atm2lnd_vars%forc_hgt_t_grc" 
     write (fid, *) atm2lnd_vars%forc_hgt_t_grc
     write (fid, "(A)") "atm2lnd_vars%forc_hgt_q_grc" 
     write (fid, *) atm2lnd_vars%forc_hgt_q_grc
     write (fid, "(A)") "atm2lnd_vars%forc_vp_grc" 
     write (fid, *) atm2lnd_vars%forc_vp_grc
     write (fid, "(A)") "atm2lnd_vars%forc_rh_grc" 
     write (fid, *) atm2lnd_vars%forc_rh_grc
     write (fid, "(A)") "atm2lnd_vars%forc_pco2_grc" 
     write (fid, *) atm2lnd_vars%forc_pco2_grc
     write (fid, "(A)") "atm2lnd_vars%forc_solad_grc" 
     write (fid, *) atm2lnd_vars%forc_solad_grc
     write (fid, "(A)") "atm2lnd_vars%forc_solai_grc" 
     write (fid, *) atm2lnd_vars%forc_solai_grc
     write (fid, "(A)") "atm2lnd_vars%forc_solar_grc" 
     write (fid, *) atm2lnd_vars%forc_solar_grc
     write (fid, "(A)") "atm2lnd_vars%forc_ndep_grc" 
     write (fid, *) atm2lnd_vars%forc_ndep_grc
     write (fid, "(A)") "atm2lnd_vars%forc_pdep_grc" 
     write (fid, *) atm2lnd_vars%forc_pdep_grc
     write (fid, "(A)") "atm2lnd_vars%forc_pc13o2_grc" 
     write (fid, *) atm2lnd_vars%forc_pc13o2_grc
     write (fid, "(A)") "atm2lnd_vars%forc_po2_grc" 
     write (fid, *) atm2lnd_vars%forc_po2_grc
     write (fid, "(A)") "atm2lnd_vars%forc_aer_grc" 
     write (fid, *) atm2lnd_vars%forc_aer_grc
     write (fid, "(A)") "atm2lnd_vars%forc_pch4_grc" 
     write (fid, *) atm2lnd_vars%forc_pch4_grc
     write (fid, "(A)") "atm2lnd_vars%forc_t_not_downscaled_grc" 
     write (fid, *) atm2lnd_vars%forc_t_not_downscaled_grc
     write (fid, "(A)") "atm2lnd_vars%forc_th_not_downscaled_grc" 
     write (fid, *) atm2lnd_vars%forc_th_not_downscaled_grc
     write (fid, "(A)") "atm2lnd_vars%forc_q_not_downscaled_grc" 
     write (fid, *) atm2lnd_vars%forc_q_not_downscaled_grc
     write (fid, "(A)") "atm2lnd_vars%forc_pbot_not_downscaled_grc" 
     write (fid, *) atm2lnd_vars%forc_pbot_not_downscaled_grc
     write (fid, "(A)") "atm2lnd_vars%forc_rho_not_downscaled_grc" 
     write (fid, *) atm2lnd_vars%forc_rho_not_downscaled_grc
     write (fid, "(A)") "atm2lnd_vars%forc_rain_not_downscaled_grc" 
     write (fid, *) atm2lnd_vars%forc_rain_not_downscaled_grc
     write (fid, "(A)") "atm2lnd_vars%forc_snow_not_downscaled_grc" 
     write (fid, *) atm2lnd_vars%forc_snow_not_downscaled_grc
     write (fid, "(A)") "atm2lnd_vars%forc_lwrad_not_downscaled_grc" 
     write (fid, *) atm2lnd_vars%forc_lwrad_not_downscaled_grc
     write (fid, "(A)") "atm2lnd_vars%forc_t_downscaled_col" 
     write (fid, *) atm2lnd_vars%forc_t_downscaled_col
     write (fid, "(A)") "atm2lnd_vars%forc_th_downscaled_col" 
     write (fid, *) atm2lnd_vars%forc_th_downscaled_col
     write (fid, "(A)") "atm2lnd_vars%forc_q_downscaled_col" 
     write (fid, *) atm2lnd_vars%forc_q_downscaled_col
     write (fid, "(A)") "atm2lnd_vars%forc_pbot_downscaled_col" 
     write (fid, *) atm2lnd_vars%forc_pbot_downscaled_col
     write (fid, "(A)") "atm2lnd_vars%forc_rho_downscaled_col" 
     write (fid, *) atm2lnd_vars%forc_rho_downscaled_col
     write (fid, "(A)") "atm2lnd_vars%forc_rain_downscaled_col" 
     write (fid, *) atm2lnd_vars%forc_rain_downscaled_col
     write (fid, "(A)") "atm2lnd_vars%forc_snow_downscaled_col" 
     write (fid, *) atm2lnd_vars%forc_snow_downscaled_col
     write (fid, "(A)") "atm2lnd_vars%forc_lwrad_downscaled_col" 
     write (fid, *) atm2lnd_vars%forc_lwrad_downscaled_col
     write (fid, "(A)") "atm2lnd_vars%forc_flood_grc" 
     write (fid, *) atm2lnd_vars%forc_flood_grc
     
     !====================== ch4_vars ======================!
     
     write (fid, "(A)") "ch4_vars%grnd_ch4_cond_patch" 
     write (fid, *) ch4_vars%grnd_ch4_cond_patch
     write (fid, "(A)") "ch4_vars%grnd_ch4_cond_col" 
     write (fid, *) ch4_vars%grnd_ch4_cond_col
     
     !====================== soilstate_vars ======================!
     
     write (fid, "(A)") "soilstate_vars%watsat_col" 
     write (fid, *) soilstate_vars%watsat_col
     write (fid, "(A)") "soilstate_vars%watdry_col" 
     write (fid, *) soilstate_vars%watdry_col
     write (fid, "(A)") "soilstate_vars%soilbeta_col" 
     write (fid, *) soilstate_vars%soilbeta_col
     call fio_close(fid) 
end subroutine write_vars